import { Router } from 'express';
import authRoutes from './auth.routes.js';
import propertyRoutes from './property.routes.js';
import clientRoutes from './client.routes.js';
import webhookRoutes from './webhook.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import conversationRoutes from './conversation.routes.js';
import appointmentRoutes from './appointment.routes.js';
import dealRoutes from './deal.routes.js';
import followUpRoutes from './followup.routes.js';
import whatsappRoutes from './whatsapp.routes.js';
import sheetsRoutes from './sheets.routes.js';
import usersRoutes from './users.routes.js';
import eventsRoutes from './events.routes.js';
import setupRoutes from './setup.routes.js';
import notificationsRoutes from './notifications.routes.js';
import settingsRoutes from './settings.routes.js';
import diagnosticsRoutes from './diagnostics.routes.js';
import uploadRoutes from './upload.routes.js';
import auditRoutes from './audit.routes.js';

const router = Router();

router.use('/setup', setupRoutes);
router.use('/auth', authRoutes);
router.use('/properties', propertyRoutes);
router.use('/clients', clientRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/conversations', conversationRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/deals', dealRoutes);
router.use('/follow-ups', followUpRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/sheets', sheetsRoutes);
router.use('/users', usersRoutes);
router.use('/events', eventsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/settings', settingsRoutes);
router.use('/diagnostics', diagnosticsRoutes);
router.use('/uploads', uploadRoutes);
router.use('/audit', auditRoutes);

export default router;
